# DAY 10 – Feature Engineering & Data Improvement

## Objective of Day 10
Till Day 9, we focused on improving Machine Learning models using tuning techniques.

In this session, we focus on **improving the DATA itself**, because in real-world ML:

**Better features matter more than better algorithms.**

By the end of this notebook, you will:
- Understand what Feature Engineering really is
- Learn why raw data is often not enough
- Create new meaningful features
- Remove weak or less useful features
- Observe how feature changes affect model performance
- Understand feature importance like industry professionals

## What is Feature Engineering?

Feature Engineering means:
- Creating better input features
- Transforming existing features
- Removing useless or noisy features

The goal is to help the model learn patterns more easily.

In [1]:
# Import required libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

## Dataset – Student Placement Data

Features:
- CGPA
- Internships
- Coding Skill

Target:
- Placement Status (1 = Placed, 0 = Not Placed)

In [2]:
data = pd.DataFrame({
    'CGPA': [7.5, 6.0, 8.2, 5.8, 9.0, 6.5, 7.8, 6.2, 8.5, 5.5],
    'Internships': [1, 0, 2, 0, 3, 1, 2, 0, 3, 0],
    'CodingSkill': [3, 1, 4, 1, 5, 2, 4, 2, 5, 1],
    'Placed': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
})

data

   CGPA  Internships  CodingSkill  Placed
0   7.5            1            3       1
1   6.0            0            1       0
2   8.2            2            4       1
3   5.8            0            1       0
4   9.0            3            5       1
5   6.5            1            2       0
6   7.8            2            4       1
7   6.2            0            2       0
8   8.5            3            5       1
9   5.5            0            1       0

## Baseline Model Using Original Features

We first train a model using raw features.

In [3]:
X = data[['CGPA', 'Internships', 'CodingSkill']]
y = data['Placed']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

baseline_pred = model.predict(X_test_scaled)
print("Baseline Accuracy:", accuracy_score(y_test, baseline_pred))

Baseline Accuracy: 1.0

## Feature Engineering – Creating a New Feature

We create a new feature that combines:
- CGPA
- Coding Skill

This represents **Academic Strength**.

In [4]:
data['AcademicStrength'] = data['CGPA'] * data['CodingSkill']

data

   CGPA  Internships  CodingSkill  Placed  AcademicStrength
0   7.5            1            3       1              22.5
1   6.0            0            1       0               6.0
2   8.2            2            4       1              32.8
3   5.8            0            1       0               5.8
4   9.0            3            5       1              45.0
5   6.5            1            2       0              13.0
6   7.8            2            4       1              31.2
7   6.2            0            2       0              12.4
8   8.5            3            5       1              42.5
9   5.5            0            1       0               5.5

## Model After Feature Engineering

Now we train the model using the new engineered feature.

In [5]:
X_new = data[['CGPA', 'Internships', 'CodingSkill', 'AcademicStrength']]
y = data['Placed']

X_train, X_test, y_train, y_test = train_test_split(
    X_new, y, test_size=0.25, random_state=42
)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model.fit(X_train_scaled, y_train)
new_pred = model.predict(X_test_scaled)

print("Accuracy After Feature Engineering:", accuracy_score(y_test, new_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, new_pred))

Accuracy After Feature Engineering: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

## Feature Importance (Logistic Regression Coefficients)

We analyze which features influence predictions the most.

In [6]:
feature_importance = pd.DataFrame({
    'Feature': X_new.columns,
    'Importance': model.coef_[0]
})

feature_importance.sort_values(by='Importance', ascending=False)

            Feature  Importance
0              CGPA    0.659649
2       CodingSkill    0.590366
1       Internships    0.571965
3  AcademicStrength    0.565533

## Key Learning from Day 10

- Feature Engineering improves model performance
- Better features help models learn faster
- New features can capture hidden patterns
- Feature importance explains model decisions
- Industry focuses more on data than algorithms